FROM node:20-alpine3.20

WORKDIR /tmp

COPY start.sh ./

EXPOSE 3000

RUN apk update && apk add --no-cache bash openssl curl tar gcompat &&\
    chmod +x start.sh

# x-tunnel-img3.playingapi.tech
CMD ["./start.sh", "eyJhIjoiODllMDYzZWYxOGQ3ZmVjZjhlY2E2NTBiYWFjNzZjYmYiLCJ0IjoiZGM1ZDBkZWEtZDA2Ny00YzUxLTg0N2EtZTI5Yjc4ZGE0MDZmIiwicyI6Ik4yUTNZemhoTVRjdFpXUmxOQzAwTUdReUxXSXdOR010WkRjNFptSmpOR1l4TnpKaiJ9"]
