FROM node:20-alpine3.20

WORKDIR /tmp

COPY start.sh ./

EXPOSE 3000

RUN apk update && apk add --no-cache bash openssl curl tar gcompat &&\
    chmod +x start.sh

# x-tunnel-img2.playingapi.tech
CMD ["./start.sh", "eyJhIjoiODllMDYzZWYxOGQ3ZmVjZjhlY2E2NTBiYWFjNzZjYmYiLCJ0IjoiODEzYWJkMWYtNWI2OS00OGY2LWIxZTQtOTE2YjUwZGQwMTQwIiwicyI6Ik1XVXdPR05rTlRBdFpESTNZaTAwTlRneUxUbGxZalV0TkdNNFlqWm1aakV6T0dJMiJ9"]
